version: '3'

services:
  web:
    build: .
    command: /bin/sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 127.0.0.1:8000"
    volumes:
      - .:/exploreNaijaAPI
    ports:
      - "8000:8000"